using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Lab2.Infrastructure.Entities;

[Table("LOCATION")]
public class Location
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   // GENERATED BY DEFAULT AS IDENTITY
    [Column("IDLOCATION")]
    public int IdLocation { get; set; }

    [Column("IDUTILISATEUR")]
    public int IdUtilisateur { get; set; }

    [Required]
    [Column("CODECOPIE")]
    [MaxLength(20)]
    public string CodeCopie { get; set; } = string.Empty;

    [Column("DATELOCATION")]
    public DateTime DateLocation { get; set; }

    [Column("DATERETOUR")]
    public DateTime? DateRetour { get; set; }   // null = location en cours

    [ForeignKey(nameof(IdUtilisateur))]
    public Client Client { get; set; } = null!;

    [ForeignKey(nameof(CodeCopie))]
    public Copie Copie { get; set; } = null!;
}
