using Lab2.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Lab2.Infrastructure.Data.Configurations;

public class LocationConfiguration : IEntityTypeConfiguration<Location>
{
    public void Configure(EntityTypeBuilder<Location> b)
    {
        b.HasKey(l => l.IdLocation);
        b.Property(l => l.IdLocation).ValueGeneratedOnAdd();   // GENERATED BY DEFAULT AS IDENTITY

        b.HasOne(l => l.Client)
            .WithMany(c => c.Locations)
            .HasForeignKey(l => l.IdUtilisateur)
            .OnDelete(DeleteBehavior.Restrict);

        b.HasOne(l => l.Copie)
            .WithMany(c => c.Locations)
            .HasForeignKey(l => l.CodeCopie)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
